## YAML Template.
---
production:
  user.management.url: http://localhost:3004
  locale: en
  village: Mtema
  gvh: Mtema
  ta: Mtema
  district: lilongwe

development:
  user.management.url: http://localhost:3004
  locale: ny
  village: Mtema
  gvh: Mtema
  ta: Mtema
  district: lilongwe

test: &TEST
  user.management.url: http://localhost:3004
  locale: ny
  village: Mtema
  gvh: Mtema
  ta: Mtema
  
dde_mode: ta

dde_ta:
  username: admin
  password: admin
  target_server: 192.168.6.173:3002
  site_code: 009
  batch_count: 10
  threshold: 5
  
dde_gvh:
  username: admin
  password: test
  target_server: localhost:3005
  site_code: 009
  batch_count: 5
  threshold: 5
  gvh: GVH Mtema
  
dde_vh:
  username: admin
  password: admin
  target_server: localhost:3005
  site_code: 009
  batch_count: 3
  threshold: 5
  gvh: GVH Mtema
  vh: VH Mtema
